---
title: "adult_mortality"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(foreign)
library(pbapply)
library(dplyr)
library(lubridate)
library(ggplot2)
source('./R/import_brazil_mortality.R')
source('./R/ts.plot.fun.R')

```

Import Data from Brazil
```{r}
#import_brazil_func()
```

```{r}
a1 <- readRDS('./Data/Brazil/Mortality/all_deaths_compiled.rds')

a1$age <- as.numeric(as.character(a1$age))
a1 <- a1[!is.na(a1$id),]

 table(a1$age_type) #What is age_type 1 or 9?

 a1$agey <- NA 
a1$agey[a1$age_type=='4' & !is.na(a1$age)]  <- a1$age[a1$age_type=='4'& !is.na(a1$age)]
a1$agey[a1$age_type=='1' & !is.na(a1$age)]  <- a1$age[a1$age_type=='1'& !is.na(a1$age)]/(24*365)

a1$agey[a1$age_type=='2' & !is.na(a1$age)]  <- a1$age[a1$age_type=='2'& !is.na(a1$age)]/365
a1$agey[a1$age_type=='3' & !is.na(a1$age)]  <- a1$age[a1$age_type=='3'& !is.na(a1$age)]/12
a1$agey[a1$age_type=='5' & !is.na(a1$age)]  <- a1$age[a1$age_type=='5'& !is.na(a1$age)]+100

hist(a1$agey)

sum(is.na(a1$agey))/nrow(a1)*100 #What percent of deaths missing an age classification?

a1$agec <- NA
a1$agec[a1$agey>=0 & a1$agey<2] <-   1 
a1$agec[a1$agey>=2 & a1$agey<5] <-   2 
a1$agec[a1$agey>=5 & a1$agey<18] <-  3 
a1$agec[a1$agey>=18 & a1$agey<40] <- 4 
a1$agec[a1$agey>=40 & a1$agey<65] <- 5 
a1$agec[a1$agey>=65 & a1$agey<80] <- 6 
a1$agec[a1$agey>=80 & a1$agey<150]<- 7 

a1$monthdate <- floor_date(a1$dod, 'month')
```

```{r}
a1$icd1 <- as.character(a1$icd1)
a1$icd2 <- as.character(a1$icd2)
a1$icd3 <- as.character(a1$icd3)
a1$icd4 <- as.character(a1$icd4)
a1$icd5 <- as.character(a1$icd5)
a1$icd6 <- as.character(a1$icd6)

a1$J12_J18_prim <- 0
a1$J12_J18_prim[grep(pattern='J12|J13|J14|J15|J16|J17|J18|J19', a1$icd1)] <- 1 #CHECK THIS

#note: code this more efficiently...
a1$J12_J18_any <- 0
a1$J12_J18_any[grep(pattern='J12|J13|J14|J15|J16|J17|J18|J19', a1$icd1)] <- 1
a1$J12_J18_any[grep(pattern='J12|J13|J14|J15|J16|J17|J18|J19', a1$icd2)] <- 1
a1$J12_J18_any[grep(pattern='J12|J13|J14|J15|J16|J17|J18|J19', a1$icd3)] <- 1
a1$J12_J18_any[grep(pattern='J12|J13|J14|J15|J16|J17|J18|J19', a1$icd4)] <- 1
a1$J12_J18_any[grep(pattern='J12|J13|J14|J15|J16|J17|J18|J19', a1$icd5)] <- 1
a1$J12_J18_any[grep(pattern='J12|J13|J14|J15|J16|J17|J18|J19', a1$icd6)] <- 1


a1$pneumococcal_pneumo=0
a1$pneumococcal_pneumo[grep(pattern='J13', a1$icd1)] <- 1
a1$pneumococcal_pneumo[grep(pattern='J13', a1$icd2)] <- 1
a1$pneumococcal_pneumo[grep(pattern='J13', a1$icd3)] <- 1
a1$pneumococcal_pneumo[grep(pattern='J13', a1$icd4)] <- 1
a1$pneumococcal_pneumo[grep(pattern='J13', a1$icd5)] <- 1
a1$pneumococcal_pneumo[grep(pattern='J13', a1$icd6)] <- 1


a1$acm_noj <- 1
a1$acm_noj[substr(a1$icd1,1,1)=='J' |
             substr(a1$icd2,1,1)=='J'|
             substr(a1$icd3,1,1)=='J'|
             substr(a1$icd4,1,1)=='J'|
             substr(a1$icd5,1,1)=='J'|
             substr(a1$icd6,1,1)=='J' ] <- 0


```


```{r}
a2 <- a1 %>%
  group_by(agec,monthdate) %>%
  summarise('J12_J18_prim'=sum(J12_J18_prim), 
            'J12_J18_any'=sum(J12_J18_any),
            'acm_noj'=sum(acm_noj),
            'pneumococcal_pneumo'=sum(pneumococcal_pneumo)
            )
```

Number of deaths due to pneumonia (any)

```{r, fig.width=8, fig.height=5}

ts.plot.fun(ds=a2,time.var='monthdate', yvar='J12_J18_any', multiple_group = T, group.var='agec', ylab1="Number of deaths due to pneumonia (any)")

```

Number of deaths due to pneumococcal pneumonia (any)

```{r, fig.width=8, fig.height=5}

ts.plot.fun(ds=a2,time.var='monthdate', yvar='pneumococcal_pneumo', multiple_group = T, group.var='agec', ylab1="Number of deaths due to pneumococcal pneumonia")

```

Proportion of deaths due to pneumonia (primary)

```{r, fig.width=8, fig.height=5}

a2$prop.j12 <- a2$J12_J18_prim/a2$acm_noj

ts.plot.fun(ds=a2,time.var='monthdate', yvar='prop.j12', multiple_group = T, group.var='agec', ylab1="Proportion of deaths due to pneumonia")

```




