---
title: "single_year analysis"
author: "Dan Weinberger"
date: '2023-03-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(MASS)
library(lubridate)
library(tidyr)
library(readxl)
```

Popsize
```{r}
pop1 <- read_excel('./Data/WPP2022_POP_F01_1_POPULATION_SINGLE_AGE_BOTH_SEXES_AR.xlsx') %>%
  reshape2::melt(., id.vars=c('country','Year')) %>%
  rename(agey=variable, pop=value, year=Year) %>%
  mutate( agey=as.character(agey),
          agey = if_else(agey=='100+','100',agey), 
          agey=as.numeric(as.character(agey)))
```


```{r, eval=F}
  a1 <- readRDS('./Data/cleaned_country_mortality_files/individual_level_data_combined.rds') %>%
    select(agey, dx1, country,  monthdate) %>%
    mutate(J12_J18 = if_else( grepl('J12', dx1)|grepl('J13', dx1)| grepl('J13', dx1)| 
                              grepl('J14', dx1)| grepl('J15', dx1)| grepl('J16', dx1)|
                              grepl('J17', dx1)| grepl('J18', dx1), 1,0 ) ,
         G30_G32 = if_else( grepl('G30', dx1)|grepl('G31', dx1)| grepl('G32', dx1), 1,0 )) %>%
  group_by(agey, country, monthdate) %>%
  summarize( J12_J18=sum(J12_J18),G30_G32=sum(G30_G32), acm=n() )

saveRDS(a1, './Data/cleaned_country_mortality_files/single_year_age.rds')

```

```{r}
a1 <- readRDS('./Data/cleaned_country_mortality_files/single_year_age.rds')

ar1 <- a1 %>%
  filter(country=='AR') %>%
    tidyr::complete(agey, monthdate, fill=list(J12_J18=0,G30_G32=0,acm=0)) %>% #fills NA
    filter(monthdate>='2005-01-01') %>%
  mutate(qtr=quarter(monthdate), 
         year=year(monthdate),
         qtrdate= year + qtr/4 -1/4) %>%
  ungroup() %>%
  group_by(agey, qtrdate) %>%
  summarize(J12_J18=sum(J12_J18),G30_G32=sum(G30_G32), acm=sum(acm)) %>%
  mutate(prop_j12= J12_J18/acm)

```
Argentina: intervention: Jan 2021; eval: 2013-2019
```{r}

ar1 %>%
  filter(agey>20 & agey<100) %>%
  ungroup() %>%
  mutate(year=floor(qtrdate)) %>%
  group_by(agey, year) %>%
  summarize(J12_J18=sum(J12_J18),G30_G32=sum(G30_G32), acm=sum(acm)) %>%
  mutate(prop_j12= J12_J18/acm) %>%
ggplot( aes(x=year, y=log(prop_j12), group=agey, color=agey)) +
  geom_line() +
  theme_classic()+
  geom_vline(xintercept=2013.0, lty=2, col='gray')
```


```{r}
ar1.mod <- ar1 %>%
  mutate(log_offset=log(acm))

mod1 <- glm.nb( J12_J18 ~ qtrdate + agey  + offset(log_offset), data=ar1.mod)

summary(mod1)

ar1.mod$pred.mod1 <- predict(mod1, type='response')

ar1.mod %>%
  mutate(prop_j12_pred= pred.mod1/acm) %>%
ggplot( aes(x=qtrdate, y=log(prop_j12_pred), group=agey, color=agey)) +
  geom_line() +
  theme_classic()+
  geom_vline(xintercept=2013.0, lty=2, col='gray')
```

```{r}

ar1.mod <- ar1 %>%
  mutate(year=floor(qtrdate)) %>%
  ungroup() %>%
  left_join(pop1, by=c('year','agey')) %>%
  arrange(agey, qtrdate) %>%
  group_by(agey) %>%
  mutate(log_acm=log(acm),
         log_pop=log(pop),
         index = row_number(),
        # intro_index = which(qtrdate==2013.0),
         vax0 = if_else(qtrdate>=2012.0 & qtrdate<2013.0,1,0),

         vax1 = if_else(qtrdate>=2013.0,1,0)
         ) %>%
  filter(agey>=80)

mod1 <- glm.nb( J12_J18 ~ index + agey  +vax0+ vax1+  offset(log_pop), data=ar1.mod)

summary(mod1)

ar1.mod$pred.mod1 <- predict(mod1, type='response', newdata=ar1.mod)

ar1.mod %>%
  mutate(prop_j12_pred= pred.mod1/acm) %>%
ggplot( aes(x=qtrdate, y=log(prop_j12_pred), group=agey, color=agey)) +
  geom_line() +
  theme_classic()+
  geom_vline(xintercept=2013.0, lty=2, col='gray')
```

or 80+ together

```{r}
ar1.mod <- ar1 %>%
  mutate(year=floor(qtrdate)) %>%
  ungroup() %>%
  filter(agey>=80) %>%
  group_by(qtrdate) %>%
  summarize(acm=sum(acm), J12_J18=sum(J12_J18) ) %>%
  
  mutate(log_acm=log(acm),
         index = row_number(),
        # intro_index = which(qtrdate==2013.0),
         vax0 = if_else(qtrdate>=2012.0 & qtrdate<2013.0,1,0),

         vax1 = if_else(qtrdate>=2013.0,1,0)
         ) %>%
  filter(agey>=80)

mod1 <- glm.nb( J12_J18 ~ index + vax0+ vax1+  offset(log_pop), data=ar1.mod)
summary(mod1)
```





